# Generated by Django 4.2.7 on 2023-11-24 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tasks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500, unique=True, verbose_name='Tarea')),
                ('priority', models.CharField(choices=[(1, 'ALTO'), (2, 'MEDIO'), (3, 'BAJO')], default=3, max_length=5, verbose_name='Prioridad')),
                ('status', models.BooleanField(choices=[(True, 'COMPLETADO'), (False, 'Pending')], default=False, verbose_name='Estado')),
                ('enable', models.BooleanField(choices=[(True, 'Habilitado'), (False, 'Inhabilitado')], default=True, verbose_name='Activo')),
            ],
            options={
                'verbose_name': 'Tarea',
                'verbose_name_plural': 'Tareas',
            },
        ),
    ]
