# Generated by Django 4.2.7 on 2023-11-24 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('to_do', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasks',
            name='priority',
            field=models.CharField(choices=[('H', 'ALTO'), ('M', 'MEDIO'), ('L', 'BAJO')], default='L', max_length=5, verbose_name='Prioridad'),
        ),
    ]
